### ISSUE TITLE
Idea: Trello management with TaskCore, or synchronize.

### ISSUE THREAD

**Issue by halilkocaoz** [tarikguney/taskcore#12]
How does that sound? I think developers and system architects who are command-line lovers can like that.

**Comment by halilkocaoz** [comment]
I started to think this feature might exterminate the simplicity of TaskCore.

**Comment by tarikguney** [comment]
It is a good idea but in the future. I still would like to keep TaskCore simple enough to do one thing right, and that is the simple todo management. Later though, TaskCore could start supporting plugins, and at that time, people can start writing plugins for TaskCore to extend its capabilities with integrations like Trello, etc. Currently, the near time plans include the integrations with cloud syncs.
