### ISSUE TITLE
Files can storable on google drive or something like that.

### ISSUE THREAD

**Issue by halilkocaoz** [tarikguney/taskcore#2]
Hello, it's not necessary now, you might think in the future.

I thought, if any user wants online storage their task, you can take permission to login google drive account and their tasks might upload there. It helps to accessibility on everywhere.

**Comment by tarikguney** [comment]
Good idea. But they can simply put the app in a local Google drive and Google drive agent can sync any new task files up to the cloud. But, perhaps, I can allow people to choose the db path so that they can choose their local Google drive.

**Comment by halilkocaoz** [comment]
Oh, I didn't know Google drive agent sync system. Anyway, I was eager to help you with that and work on the TaskCore. If you have any 'junior' developer task, I can take care of it 🦅 

thanks in advance.

**Comment by tarikguney** [comment]
Sure thing! Thanks for the offer 👍
