### ISSUE TITLE
The program exited with code 0 on error

### ISSUE THREAD

**Issue by navarroaxel** [tarikguney/taskcore#9]
If the command fails the program exited with code 0:

```bash
$ taskcore addc -t Work && echo "Success!"
Category "Work" already exists. Please use a different category name. Remember, the category names are not case sensitive.
Success!
```

The `Success!` message should not be printed.

**Comment by tarikguney** [comment]
Good catch. I will address it.

**Comment by tarikguney** [comment]
Fixed in https://github.com/tarikguney/taskcore/commit/5a0d2d0646ce4c957ff0a15eb934193b0648df1b
